### ISSUE TITLE
Location not available after disabling on initial install

### ISSUE THREAD

**Issue by c3bryant** [UCSD/now-mobile#97]
### Issue Description
Location not available after disabling on initial install

### Steps to Reproduce / Code Snippets

1) Uninstall and reinstall the app
2) Load the app, the user is prompted at load to allow access to their location
3) Click 'No', some of the cards will now show a message with a button linking to the Location Settings page
4) Click the Location Settings button or navigate to the Location Settings page normally
5) Enable Location Settings for now-mobile
5) Return to the app, Location Settings still appear to be disabled
6) Force close and reload the app, Location Settings appear to be disabled

### Additional Information
* Platform(s) (iOS, Android, or both?): iOS (possibly Android, need more testing)

**Comment by i8wu** [comment]
Found 2 problems and would like to brainstorm ideas a bit, would be cool to get some input from everyone @jpknoll @srkirkland @c3bryant 

Problem 1 - Autorehydrate ends up running after geoLocationContainer is mounted, which causes the older `location: denied` to override the newer state with `location: authorized` This is why even on app restart the denied permission is persisting.
I have a solution involving the currently unused `this.state.isLoading` in app/index.js

```
let geolocation = null;
if (!this.state.isLoading) {
	geolocation = (<GeoLocationContainer />);
}

return (
	<Provider store={this.state.store}>
		<View style={css.flex}>
			{geolocation}
			{navigator}
		</View>
	</Provider>
);
```

2 - I don’t see anywhere permission is rechecked, so without an app restart the user won't be able to have access to location based cards. I’m thinking maybe something with app resume && location.permission == denied

Thanks!

**Comment by srkirkland** [comment]
@c3bryant @i8wu @jpknoll  For problem 1, I like the solution although I think everything should not load until the auto rehydrate is done, not just the geo location container.  Basically that entire view should not return anything until the rehydrate is done, similar to how the F8 app does it.  Currently this is difficult because the navigation references are attached on app load, instead of component create, but some refactoring would make that all work nicely.

2: This part is true, there is no recheck, so an app resume permissions check is probably the best bet like you say.

**Comment by jpknoll** [comment]
Playing around with the newer version of android: The new permissions look similar to iPhone. So the user will get request window + can go into settings and revoke permission.

So! We should probably not auto rehydrate anything related to the geolocation component. 

1. User says no to request
2. App Unloads
3. User reloads app
4. We do a standard get permission status; on unknown value, we perform another soft ask.

@srkirkland Is there a way to get the rehydrate state and return null on the component until we're loaded, similar to F8, or otherwise not rehydrate the geolocation component in some way?

**Comment by jpknoll** [comment]
Playing around with the newer version of android: The new permissions look similar to iPhone. So the user will get request window + can go into settings and revoke permission.

So! We should probably not auto rehydrate anything related to the geolocation component.

User says no to request
App Unloads
User reloads app
We do a standard get permission status; on unknown value, we perform another soft ask.
@srkirkland Is there a way to get the rehydrate state and return null on the component until we're loaded, similar to F8, or otherwise not rehydrate the geolocation component in some way?

**Comment by jpknoll** [comment]
Looks like we can whitelist store properties. So we won't whitelist location!

**Comment by srkirkland** [comment]
@jpknoll yup, let's whitelist only the card store (and eventually logged in user info).

  persistStore(store, { storage: AsyncStorage, whitelist: ['user', 'cards'] }, onComplete);

**Comment by jpknoll** [comment]
@srkirkland I don't see a user reducer just yet. You'll want to add that on your branch after this merge.

**Comment by srkirkland** [comment]
@jpknoll yea, it was just an example, we don't need to keep user stuff until we get logins working.
