### ISSUE TITLE
Load components after re-hydrate

### ISSUE THREAD

**Issue by i8wu** [UCSD/now-mobile#98]
Issues may be caused by components rendering/mounting before the redux store rehydrate happens. #97 

Refactor code to have app in a loading state without any components until rehydration occurs.

**Comment by srkirkland** [comment]
@i8wu Let me know if you want some help with this, I'd be happy to take a look

**Comment by i8wu** [comment]
@srkirkland Sure, but just thought about it a bit and is there much we need to do besides stopping the navigator rendering until after rehydrate?

**Comment by srkirkland** [comment]
@i8wu Not sure what you need, but just read this issue and I think that'd be the big thing, since the navigation rendering is what in turn loads the home view.

**Comment by jpknoll** [comment]
Playing around with the newer version of android: The new permissions look similar to iPhone. So the user will get request window + can go into settings and revoke permission.

So! We should probably not auto rehydrate anything related to the geolocation component.

1. User says no to request
2. App Unloads
3. User reloads app
4. We do a standard get permission status; on unknown value, we perform another soft ask.

@srkirkland Is there a way to get the rehydrate state and return null on the component until we're loaded, similar to F8, or otherwise not rehydrate the geolocation component in some way?
